import 'package:flutter/material.dart';

/// Three kinds of thing you can send. Named for what the artwork actually
/// *is*: a bouquet or bloom is a flower; a place is a scene; a single
/// illustrated bloom cut out on nothing is a stem. Mislabelling a meadow as
/// a species reads as sloppy, so the split is honest instead.
///
/// The stems are the same artwork the bouquet builder on the website draws
/// from — see `tool/slice_stems.py`. One drawing of a tulip, in both places.
enum FlowerCategory {
  flower,
  scene,
  stem;

  String get label => switch (this) {
        flower => 'Flowers',
        scene => 'Scenes',
        stem => 'Stems',
      };
}

/// Something the sender can pick. `id` is the stable string stored in
/// `flower_messages.flower_type` — **never rename an existing id**, old
/// messages reference them.
class Flower {
  const Flower({
    required this.id,
    required this.emoji,
    required this.name,
    required this.color,
    required this.meaning,
    required this.category,
    this.retired = false,
    this.cutout = false,
  });

  final String id;

  /// Fallback glyph — used by the home-screen widget, and in-app whenever
  /// [asset] is missing from the bundle.
  final String emoji;

  final String name;
  final Color color;
  final String meaning;
  final FlowerCategory category;

  /// Kept so old messages still resolve, but hidden from the picker.
  final bool retired;

  /// Whether the artwork is a cut-out on transparency rather than a
  /// photograph that fills its frame.
  ///
  /// ⚠️ Decides how it is drawn, not just how it looks: a cut-out stem is
  /// tall and narrow, and `cover` in a square box crops the bloom clean off
  /// the top. See [FlowerImage].
  final bool cutout;

  /// Artwork path, by convention `<id>.webp`. Render with `FlowerImage`,
  /// which falls back to [emoji] if the file isn't there.
  String get asset => 'assets/images/flowers/$id.webp';
}

class FlowerCatalog {
  /// Everything, including retired entries. Use [pickable] for the picker.
  static const all = <Flower>[
    // ── Flowers ────────────────────────────────────────────
    Flower(
      id: 'classic_tulip',
      emoji: '🌷',
      name: 'Classic Tulips',
      color: Color(0xFFD64270),
      meaning: 'Declaration of love',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'roses_and_tulips',
      emoji: '🌹',
      name: 'Roses & Tulips',
      color: Color(0xFFC81E4A),
      meaning: 'I still choose you',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'red_tulips',
      emoji: '🌷',
      name: 'Red Tulips',
      color: Color(0xFFD8324B),
      meaning: 'Thinking of you all day',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'peach_tulips',
      emoji: '🌷',
      name: 'Peach Tulips',
      color: Color(0xFFF0A085),
      meaning: 'Something gentle for today',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'lavender_roses',
      emoji: '💜',
      name: 'Lavender Roses',
      color: Color(0xFF9B7FD4),
      meaning: 'You are on my mind',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'tulips_and_lilies',
      emoji: '🪷',
      name: 'Tulips & Lilies',
      color: Color(0xFFEFB8C8),
      meaning: 'Soft place to land',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'tulip_protea',
      emoji: '💐',
      name: 'Tulip & Protea',
      color: Color(0xFFCE5A8E),
      meaning: 'Something rare, like you',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'wrapped_bouquet',
      emoji: '💐',
      name: 'Wrapped Bouquet',
      color: Color(0xFF9C6BAF),
      meaning: 'Wish I could hand you this',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'bouquet',
      emoji: '💐',
      name: 'Full Bouquet',
      color: Color(0xFFE8722A),
      meaning: 'You mean everything',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'seaside_posy',
      emoji: '🌼',
      name: 'Seaside Posy',
      color: Color(0xFFE8B94A),
      meaning: 'Somewhere we should go',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'driftwood_posy',
      emoji: '🌼',
      name: 'Driftwood Posy',
      color: Color(0xFFD9A84E),
      meaning: 'Slow morning, thinking of us',
      category: FlowerCategory.flower,
    ),
    Flower(
      id: 'terrace_tulips',
      emoji: '🌷',
      name: 'Terrace Tulips',
      color: Color(0xFFE0522F),
      meaning: 'Ordinary day, still yours',
      category: FlowerCategory.flower,
    ),

    // ── Scenes ─────────────────────────────────────────────
    Flower(
      id: 'sunlit_wood',
      emoji: '🌲',
      name: 'Sunlit Wood',
      color: Color(0xFFD9713F),
      meaning: 'A good morning to you',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'garden_path',
      emoji: '🪻',
      name: 'Garden Path',
      color: Color(0xFF8E7BC8),
      meaning: 'Walk it with me',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'jungle_bloom',
      emoji: '🦜',
      name: 'Jungle Bloom',
      color: Color(0xFF2E8B57),
      meaning: 'Somewhere wild together',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'lavender_doves',
      emoji: '🕊️',
      name: 'Lavender & Doves',
      color: Color(0xFF9A86D6),
      meaning: 'Peace, wherever you are',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'paradise_grove',
      emoji: '🌺',
      name: 'Paradise Grove',
      color: Color(0xFFE2445C),
      meaning: 'Running away with you',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'sunset_shore',
      emoji: '🌅',
      name: 'Sunset Shore',
      color: Color(0xFFE9A05C),
      meaning: 'Same sun, different window',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'canyon_poppies',
      emoji: '🏜️',
      name: 'Canyon Poppies',
      color: Color(0xFFE07B39),
      meaning: 'Even the dry places bloom',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'misty_grove',
      emoji: '🌫️',
      name: 'Misty Grove',
      color: Color(0xFF9E86A8),
      meaning: 'Quiet day, loud heart',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'blossom_heron',
      emoji: '🌸',
      name: 'Blossom & Heron',
      color: Color(0xFFEFA8BE),
      meaning: 'Stillness I wish we shared',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'fox_in_tulips',
      emoji: '🦊',
      name: 'Fox in the Tulips',
      color: Color(0xFFE08A6A),
      meaning: 'Something small made me smile',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'cliffside_bloom',
      emoji: '🌊',
      name: 'Cliffside Bloom',
      color: Color(0xFF4E9FC4),
      meaning: 'Miles of sea, still close',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'lavender_fields',
      emoji: '💜',
      name: 'Lavender Fields',
      color: Color(0xFF8B72E0),
      meaning: "Rest — I've got you",
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'highland_tulips',
      emoji: '⛰️',
      name: 'Highland Tulips',
      color: Color(0xFFDE8FA6),
      meaning: 'Worth the long way',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'desert_bloom',
      emoji: '🐢',
      name: 'Desert Bloom',
      color: Color(0xFFE09240),
      meaning: 'Slow and certain, like us',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'alpine_meadow',
      emoji: '🦅',
      name: 'Alpine Meadow',
      color: Color(0xFF5B8DEF),
      meaning: 'Thinking big of you',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'deer_clearing',
      emoji: '🦌',
      name: 'Deer Clearing',
      color: Color(0xFF7FA05C),
      meaning: 'Gentle day to you',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'quiet_woodland',
      emoji: '🌿',
      name: 'Quiet Woodland',
      color: Color(0xFF6C9A6E),
      meaning: 'Nothing to say, just here',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'misty_blossom',
      emoji: '🌸',
      name: 'Misty Blossom',
      color: Color(0xFFE9AFC6),
      meaning: 'Soft start to the day',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'bench_in_bloom',
      emoji: '🪑',
      name: 'Bench in Bloom',
      color: Color(0xFFB3894F),
      meaning: 'Saving you a seat',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'mountain_spring',
      emoji: '🏔️',
      name: 'Mountain Spring',
      color: Color(0xFF4A7FD4),
      meaning: 'Fresh start, together',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'fawn_butterflies',
      emoji: '🦋',
      name: 'Fawn & Butterflies',
      color: Color(0xFFCE93D8),
      meaning: 'You make it lighter',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'morning_meadow',
      emoji: '🌾',
      name: 'Morning Meadow',
      color: Color(0xFFA8B87A),
      meaning: 'First thought was you',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'dappled_light',
      emoji: '✨',
      name: 'Dappled Light',
      color: Color(0xFFD9B84E),
      meaning: 'Little bit of sun for you',
      category: FlowerCategory.scene,
    ),
    Flower(
      id: 'wildflower_haze',
      emoji: '🌸',
      name: 'Wildflower Haze',
      color: Color(0xFFC77BA8),
      meaning: 'Dreaming in your direction',
      category: FlowerCategory.scene,
    ),

    // ── Stems ──────────────────────────────────────────────
    // The bouquet builder's single blooms, cut out of the same sprite sheets
    // the website draws from — see tool/slice_stems.py. Illustrations rather
    // than photographs, so they are `cutout: true` and drawn `contain`ed.
    //
    // ⚠️ The ids are derived from the website's names. That list is frozen
    // (gift links store a flower's index), so these are stable too — but a
    // rename there would silently orphan every message sent with the old id.
    // Never rename one; retire it and add the new one, as below.
    Flower(
      id: 'stem_tulip',
      emoji: '🌸',
      name: 'Tulip',
      color: Color(0xFFE89CB4),
      meaning: 'A little love',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_rose',
      emoji: '🌸',
      name: 'Rose',
      color: Color(0xFFA54765),
      meaning: 'Always you',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_daisy',
      emoji: '🌸',
      name: 'Daisy',
      color: Color(0xFFDFBE63),
      meaning: 'Just because',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_sunflower',
      emoji: '🌸',
      name: 'Sunflower',
      color: Color(0xFFDFA63D),
      meaning: 'You are sunshine',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_lavender',
      emoji: '🌸',
      name: 'Lavender',
      color: Color(0xFF9F88C5),
      meaning: 'A moment of calm',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_peony',
      emoji: '🌸',
      name: 'Peony',
      color: Color(0xFFD994B1),
      meaning: 'Something lovely',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_lily',
      emoji: '🌸',
      name: 'Lily',
      color: Color(0xFFE8E2D6),
      meaning: 'Pure and true',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_orchid',
      emoji: '🌸',
      name: 'Orchid',
      color: Color(0xFFC473C0),
      meaning: 'Rare, like you',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_hydrangea',
      emoji: '🌸',
      name: 'Hydrangea',
      color: Color(0xFFE58AB0),
      meaning: 'A whole armful',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_gerbera',
      emoji: '🌸',
      name: 'Gerbera',
      color: Color(0xFFE87A2A),
      meaning: 'Instant cheer',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_carnation',
      emoji: '🌸',
      name: 'Carnation',
      color: Color(0xFFE5697C),
      meaning: 'Sweet and steady',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_poppy',
      emoji: '🌸',
      name: 'Poppy',
      color: Color(0xFFD9382A),
      meaning: 'A bright hello',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_anemone',
      emoji: '🌸',
      name: 'Anemone',
      color: Color(0xFF7B6FD0),
      meaning: 'Soft and brave',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_ranunculus',
      emoji: '🌸',
      name: 'Ranunculus',
      color: Color(0xFFE8902A),
      meaning: 'Layers of lovely',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_dahlia',
      emoji: '🌸',
      name: 'Dahlia',
      color: Color(0xFFD63A86),
      meaning: 'Bold and kind',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_iris',
      emoji: '🌸',
      name: 'Iris',
      color: Color(0xFF3F5FD0),
      meaning: 'Good news soon',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_calla_lily',
      emoji: '🌸',
      name: 'Calla lily',
      color: Color(0xFFEEE9DC),
      meaning: 'Simply elegant',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_camellia',
      emoji: '🌸',
      name: 'Camellia',
      color: Color(0xFFE8769F),
      meaning: 'My admiration',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_daffodil',
      emoji: '🌸',
      name: 'Daffodil',
      color: Color(0xFFE8C02A),
      meaning: 'New beginnings',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_gardenia',
      emoji: '🌸',
      name: 'Gardenia',
      color: Color(0xFFEEE8DC),
      meaning: 'A secret joy',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_magnolia',
      emoji: '🌸',
      name: 'Magnolia',
      color: Color(0xFFE195B4),
      meaning: 'Gentle strength',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_jasmine',
      emoji: '🌸',
      name: 'Jasmine',
      color: Color(0xFFEAE6D8),
      meaning: 'Sweet on you',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_sweet_pea',
      emoji: '🌸',
      name: 'Sweet pea',
      color: Color(0xFFE6E0D4),
      meaning: 'Thank you for today',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_delphinium',
      emoji: '🌸',
      name: 'Delphinium',
      color: Color(0xFF4A63C4),
      meaning: 'Reaching for you',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_snapdragon',
      emoji: '🌸',
      name: 'Snapdragon',
      color: Color(0xFFE892A8),
      meaning: 'Playful and strong',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_cornflower',
      emoji: '🌸',
      name: 'Cornflower',
      color: Color(0xFF4A6AD0),
      meaning: 'A small blue wish',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_cosmos',
      emoji: '🌸',
      name: 'Cosmos',
      color: Color(0xFFE9E4DA),
      meaning: 'Peace and quiet',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_zinnia',
      emoji: '🌸',
      name: 'Zinnia',
      color: Color(0xFFE0588E),
      meaning: 'Thinking of you',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_marigold',
      emoji: '🌸',
      name: 'Marigold',
      color: Color(0xFFE8801F),
      meaning: 'Warm as the sun',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_aster',
      emoji: '🌸',
      name: 'Aster',
      color: Color(0xFF9A7AD0),
      meaning: 'Patient love',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_chrysanthemum',
      emoji: '🌸',
      name: 'Chrysanthemum',
      color: Color(0xFFECE8DC),
      meaning: 'Long life and joy',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_lisianthus',
      emoji: '🌸',
      name: 'Lisianthus',
      color: Color(0xFFE284A6),
      meaning: 'Quietly devoted',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_freesia',
      emoji: '🌸',
      name: 'Freesia',
      color: Color(0xFFE88FAE),
      meaning: 'Trust and friendship',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_alstroemeria',
      emoji: '🌸',
      name: 'Alstroemeria',
      color: Color(0xFFD63C34),
      meaning: 'Our little bond',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_scabiosa',
      emoji: '🌸',
      name: 'Scabiosa',
      color: Color(0xFF7F8FD0),
      meaning: 'I remember',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_stock',
      emoji: '🌸',
      name: 'Stock',
      color: Color(0xFFA87AD0),
      meaning: 'A lasting bond',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_amaryllis',
      emoji: '🌸',
      name: 'Amaryllis',
      color: Color(0xFFD02F2F),
      meaning: 'Proud of you',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_hyacinth',
      emoji: '🌸',
      name: 'Hyacinth',
      color: Color(0xFF5A76D4),
      meaning: 'Play and springtime',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_muscari',
      emoji: '🌸',
      name: 'Muscari',
      color: Color(0xFF6A80D0),
      meaning: 'Small and certain',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_allium',
      emoji: '🌸',
      name: 'Allium',
      color: Color(0xFFA86AD0),
      meaning: 'Wonderfully odd',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_hellebore',
      emoji: '🌸',
      name: 'Hellebore',
      color: Color(0xFFA8C07A),
      meaning: 'Steady in winter',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_lily_of_the_valley',
      emoji: '🌸',
      name: 'Lily of the valley',
      color: Color(0xFFEBE7DB),
      meaning: 'Happiness returns',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_forget_me_not',
      emoji: '🌸',
      name: 'Forget-me-not',
      color: Color(0xFF6A92D8),
      meaning: 'Don\'t forget me',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_babys_breath',
      emoji: '🌸',
      name: 'Baby\'s breath',
      color: Color(0xFFECE9DF),
      meaning: 'Everlasting',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_protea',
      emoji: '🌸',
      name: 'Protea',
      color: Color(0xFFD6607E),
      meaning: 'Brave and rare',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_bird_of_paradise',
      emoji: '🌸',
      name: 'Bird of paradise',
      color: Color(0xFFE8801F),
      meaning: 'Somewhere far',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_anthurium',
      emoji: '🌸',
      name: 'Anthurium',
      color: Color(0xFFE0778C),
      meaning: 'Open-hearted',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_lotus',
      emoji: '🌸',
      name: 'Lotus',
      color: Color(0xFFE38FB0),
      meaning: 'A calm start',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_craspedia',
      emoji: '🌸',
      name: 'Craspedia',
      color: Color(0xFFE8C62A),
      meaning: 'A pocket of sun',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_snowdrop',
      emoji: '🌸',
      name: 'Snowdrop',
      color: Color(0xFFEBE8DE),
      meaning: 'Hope, early',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_crocus',
      emoji: '🌸',
      name: 'Crocus',
      color: Color(0xFF9A72C8),
      meaning: 'First of spring',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_agapanthus',
      emoji: '🌸',
      name: 'Agapanthus',
      color: Color(0xFF5F7ACE),
      meaning: 'Love letters',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_bleeding_heart',
      emoji: '🌸',
      name: 'Bleeding heart',
      color: Color(0xFFE0708F),
      meaning: 'All my heart',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    Flower(
      id: 'stem_mimosa',
      emoji: '🌸',
      name: 'Mimosa',
      color: Color(0xFFE8C73A),
      meaning: 'A soft surprise',
      category: FlowerCategory.stem,
      cutout: true,
    ),
    // ── Retired ────────────────────────────────────────────
    // No artwork in the set matches these, but flower_messages rows still
    // reference them. Kept so history renders correctly; hidden from the
    // picker so nobody sends a lone emoji among the photographs.
    Flower(
      id: 'sunflower',
      emoji: '🌻',
      name: 'Sunflower',
      color: Color(0xFFE8922A),
      meaning: 'Always watching',
      category: FlowerCategory.flower,
      retired: true,
    ),
    Flower(
      id: 'hibiscus',
      emoji: '🌺',
      name: 'Hibiscus',
      color: Color(0xFFEF4444),
      meaning: 'Rare beauty',
      category: FlowerCategory.flower,
      retired: true,
    ),
  ];

  /// What the picker offers.
  static final pickable = all.where((f) => !f.retired).toList();

  static final _byId = {for (final f in all) f.id: f};

  /// Falls back to the classic tulip for unknown ids so old messages
  /// never crash the UI.
  static Flower byId(String id) => _byId[id] ?? all.first;
}
