export const guideDate = "2026-09-27T00:00:00+04:00";

export const guides = {
  "digital-bouquet-messages": {
    title: "Digital bouquet messages: 12 notes to make your own",
    description: "Find short digital bouquet messages for birthdays, thank-yous, long-distance love, and just because, with simple ways to make each note personal.",
    intro: "A digital bouquet message can be short: name the reason you thought of them, add one detail only you would notice, and sign your name. These twelve original notes are starting points, not a script you need to follow.",
    minutes: 4,
    tool: "/bouquet", action: "Make a free digital bouquet",
    sections: [
      { id: "just-because", title: "For no occasion at all", paragraphs: ["You do not need a big reason to send flowers. Start with a real moment: a song, a shared joke, or something you wished they had been there to see. Replace the detail in these examples with yours."], bullets: ["I passed our coffee place and thought of you. These felt more fun than another ‘wish you were here’ text.", "No occasion. Just a small reminder that I like doing ordinary life with you.", "A little color for your screen, because you brought some to my day."] },
      { id: "birthday", title: "For their birthday", paragraphs: ["Make the note about the person, rather than describing how beautiful your bouquet is. Mention something you appreciate or a specific plan you would like to share. If you cannot be there, acknowledge it without making them responsible for cheering you up."], bullets: ["Happy birthday to my favorite person to get wonderfully lost with. Here’s to another year of our little adventures.", "I wish I could hand these to you over breakfast. For now, happy birthday from my side of the world.", "Today is a good excuse to say it: I’m so glad I know you. Happy birthday, [name]."] },
      { id: "long-distance", title: "For someone you miss", paragraphs: ["A time-zone detail can make a simple note feel personal. Say what you wanted to share, and let the message stand on its own if they are asleep or busy. A gift does not need a reply deadline."], bullets: ["It’s evening here and probably breakfast there. A few flowers to meet you at the start of your day.", "I saved you a little piece of today. The longer version is waiting for our next call.", "One day these will be on the same kitchen table. Until then, a bouquet from my screen to yours."] },
      { id: "thank-you", title: "To say thank you", paragraphs: ["Name what they did and why it mattered. ‘Thanks for listening when I was overwhelmed’ tells them more than ‘thanks for everything.’ You can use this structure for a friend, partner, family member, or colleague."], bullets: ["Thank you for listening yesterday. You made a difficult day feel less lonely.", "For the lift, the snacks, and all the little ways you show up. I noticed. Thank you.", "You remembered the thing I thought everyone had forgotten. These are a small thank-you for that."] },
      { id: "personalize", title: "Make any note sound like you", paragraphs: ["Read your note aloud. If it sounds like something you would never say, simplify it. Swap a general compliment for a memory: the train you nearly missed, the meal they made, or the voice note that made you laugh.", "Keep the main thought to one or two sentences so it is comfortable to read on a phone. You can add their name and your signature separately in the bouquet creator. A photo can carry a second memory without making the message longer.", "Avoid making promises you cannot keep. For an apology, say what you are sorry for directly; flowers can accompany that conversation, but they cannot replace it."] },
      { id: "send", title: "Add your note and send the bouquet", paragraphs: ["Open the free Dayflower bouquet creator, choose and arrange the flowers, then add your photo and message. Preview your gift before creating the link. Copy it into your usual chat, or download the bouquet as a PNG.", "The recipient does not need a Dayflower account. Anyone with the gift link can open it, so share it with the intended person rather than posting a personal note publicly. Gift links last about 400 days; download the image if you want a lasting copy."] },
    ],
  },
  "how-to-make-photo-strips": {
    title: "How to make photo strips online for free",
    description: "Make a photo strip from your camera or uploaded photos. Choose a solo or couple layout, fix crops, add a caption, and download a PNG without signing up.",
    intro: "To make a photo strip online, open the Dayflower photo booth, choose a layout, fill the photo slots, and select Create my image. You can use your camera or existing pictures, and download the finished PNG for free without an account.",
    minutes: 5,
    tool: "/photobooth", action: "Open the free online photo booth",
    sections: [
      { id: "layout", title: "1. Choose a layout for the photos you have", paragraphs: ["Start with the number of pictures rather than the frame color. The original is a classic three-photo strip. On film holds four photos. You & me has six slots, arranged as two columns of three, which works well when you are combining photos from two people.", "If you want more than a strip, Little things is a four-photo scrapbook and Life lately is a nine-photo recap. You do not need to shoot new pictures for every layout; existing JPG, PNG, or WebP photos work too."], bullets: ["Three portraits: The original, 1080 × 1920 PNG.", "Four moments: On film, 1080 × 1920 PNG.", "Two people, three photos each: You & me, 1080 × 1920 PNG.", "A two-photo postcard: A postcard for you, 1080 × 1350 PNG."] },
      { id: "photos", title: "2. Add photos or use your camera", paragraphs: ["Select a photo slot and upload a picture from your device, or use the camera option. Camera capture needs your browser’s permission and includes a three-second countdown. If permission is denied or the camera is unavailable, uploading existing photos is an equally good option.", "For a consistent strip, face a window or another soft light source and keep the camera at roughly the same height. Leave a little space around faces; a wide source image may need cropping to fit a narrower frame. For variety, try one smile, one silly expression, and one close-up detail.", "For a long-distance couple strip, exchange the chosen photos through your normal chat and collect them on one device. Add one person to column A and the other to column B. This is a shared-photo layout, not a live camera room connecting two devices."] },
      { id: "crop", title: "3. Adjust the crop before styling", paragraphs: ["Check every photo in the preview. Use the zoom and position controls to keep eyes, faces, and important details inside the frame. If the crop feels cramped even at the lowest zoom, choose another photo with more space around the subject.", "Next choose Rose, Cream, After dark, or Lilac. Try black and white if your photos have very different lighting. Add a short caption, such as a date, place, or a phrase you both use. Keeping it brief gives the photos room to do the talking."] },
      { id: "download", title: "4. Create and download your PNG", paragraphs: ["Fill every slot, then select Create my image and Download PNG. Story layouts are 1080 × 1920 pixels; feed layouts are 1080 × 1350. The exported image uses the same design and crops as the preview.", "On devices that support sharing files, Share image opens your device’s share menu. Otherwise, download the PNG and attach it from your files or photos app. Send the file rather than a screenshot if you want to preserve the exported resolution.", "If you plan to print it, check the crop and paper size in your print dialog. These are story- and feed-sized images, so fitting them to a different paper shape can add margins or cut off edges."] },
      { id: "troubleshooting", title: "If something is not working", paragraphs: ["If the camera does not open, check the browser’s camera permission for the site, or use Upload instead. If a photo will not import, try a JPG, PNG, or WebP version. Some phone photo formats may need to be exported to one of those formats first.", "If you cannot create the image, check for an empty slot. If your saved image looks cropped in a messaging app, open the actual file: chat previews may use a different aspect ratio. When a download does not appear in your gallery, check the device’s Downloads folder."] },
      { id: "privacy", title: "What happens to your photos?", paragraphs: ["Dayflower’s photo booth processes your pictures in your browser. It does not upload them to a server or keep an online gallery. Clear all photos or close the page when you are done; downloaded files remain on your device.", "Sharing is a separate step: the app or person you choose receives the image. Check that everyone pictured is comfortable with where you plan to share it, especially if the final strip will be public."] },
    ],
  },
} as const;

export type GuideSlug = keyof typeof guides;
