import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "../components/SiteHeader";
import { JsonLd, openGraph, url, WEBSITE } from "../lib/seo";
import { guides } from "./guides";

const title = "Date Ideas, Digital Gift Notes & Photo Guides | Dayflower";
const description = "Practical long-distance date ideas, digital bouquet message examples, and photo strip tutorials. Small plans and things you can make for someone you love.";
export const metadata: Metadata = { title, description, alternates: { canonical: url("/journal") }, openGraph: openGraph({ title, description, path: "/journal" }) };
const articles = [
  { slug: "long-distance-date-ideas", title: "7 long-distance date ideas for a quiet night in", description: "Choose a plan by time, energy, and whether your schedules overlap. Each idea includes steps and a conversation prompt.", category: "Date ideas", date: "Updated September 27, 2026" },
  ...Object.entries(guides).map(([slug, guide]) => ({ slug, title: guide.title, description: guide.description, category: "Practical guides", date: "September 27, 2026" })),
];
export default function Journal() {
  return <><SiteHeader /><main className="site-page mx-auto min-h-[70vh] max-w-5xl px-5 py-12 sm:py-20"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-dark">Dayflower Journal</p><h1 className="mt-5 max-w-3xl text-4xl font-bold leading-tight sm:text-5xl">Date ideas, thoughtful notes,<br />and things to make together.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-body">For the nights you have twenty minutes, the message you cannot quite write, and the photos you want to keep. Start with something small.</p><div className="mt-10 grid gap-6 sm:grid-cols-2">{articles.map(article => <article key={article.slug} className="flex flex-col rounded-3xl border border-border-soft bg-surface p-7"><p className="text-xs font-semibold text-body">{article.category} · {article.date}</p><h2 className="mt-4 text-2xl font-bold leading-snug"><Link href={`/journal/${article.slug}`} className="hover:underline">{article.title}</Link></h2><p className="my-5 leading-relaxed text-body">{article.description}</p><Link href={`/journal/${article.slug}`} className="mt-auto inline-flex min-h-11 items-center font-bold text-brand-dark underline underline-offset-4">Read the guide →</Link></article>)}</div><p className="mt-10 max-w-2xl leading-relaxed text-body">Planning around different clocks? Our <Link href="/long-distance" className="font-bold text-brand-dark underline underline-offset-4">guide for long-distance couples</Link> brings together ideas for time zones, date nights, and free digital gifts.</p></main><footer className="mx-auto flex max-w-5xl flex-wrap gap-6 px-5 py-8 text-sm text-body"><Link href="/">Dayflower</Link><Link href="/bouquet">Digital bouquet creator</Link><Link href="/photobooth">Online photo booth</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></footer><JsonLd nodes={[{ "@type": "CollectionPage", "@id": url("/journal#webpage"), url: url("/journal"), name: title, description, isPartOf: { "@id": WEBSITE["@id"] } }, { "@type": "ItemList", name: "Dayflower Journal guides", itemListElement: articles.map((article, i) => ({ "@type": "ListItem", position: i + 1, name: article.title, url: url(`/journal/${article.slug}`) })) }]} /></>;
}
