import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "../components/SiteHeader";
import { openGraph, url } from "../lib/seo";

const description = "Practical date ideas and small ways to share everyday life, for couples together or far apart.";
export const metadata: Metadata = { title: "Dayflower Journal | Little ways to stay close", description, alternates: { canonical: url("/journal") }, openGraph: openGraph({ title: "Dayflower Journal | Little ways to stay close", description, path: "/journal" }) };
export default function Journal() {
  return <><SiteHeader /><main className="mx-auto min-h-[70vh] max-w-5xl px-5 py-16 sm:py-24"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-dark">Dayflower Journal</p><h1 className="mt-5 max-w-2xl text-4xl font-bold leading-tight sm:text-5xl">Little ways to stay close.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-body">Ideas for sharing everyday life, whether you are across the sofa or across time zones.</p><article className="mt-12 max-w-2xl rounded-3xl border border-border-soft bg-surface p-7 sm:p-10"><p className="text-sm font-semibold text-brand-dark">Date ideas · September 8, 2026</p><h2 className="mt-4 text-2xl font-bold leading-snug"><Link href="/journal/long-distance-date-ideas" className="hover:underline">7 long-distance date ideas for a quiet night in</Link></h2><p className="my-5 leading-relaxed text-body">Simple plans for tired evenings, different time zones, and making a little memory together.</p><Link href="/journal/long-distance-date-ideas" className="font-bold text-brand-dark underline underline-offset-4">Read the article →</Link></article><p className="mt-10 max-w-2xl leading-relaxed text-body">More on being apart: our <Link href="/long-distance" className="font-bold text-brand-dark underline underline-offset-4">guide for long-distance couples</Link> covers planning around a time difference and the free tools for sending something across it.</p></main><footer className="mx-auto flex max-w-5xl flex-wrap gap-6 px-5 py-8 text-sm text-body"><Link href="/">Dayflower</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></footer></>;
}
