"""Generates android/app/src/main/res/raw/alarm.ogg — the reminder alarm tone.

Run from the repo root:  python tools/generate_alarm_wav.py

Needs ffmpeg on the PATH, with libvorbis.

🔴 **Ogg Vorbis, not WAV.** Thirty seconds of 16-bit WAV was 1.3 MB, the
largest single file in the APK after the native libraries, and the APK has a
hard 50 MiB ceiling (tool/publish_update.dart). As Vorbis it is about 30 KB
and sounds the same: it is four beeps and silence. Android names a raw
resource without its extension, so the sound is still `alarm` to
ReminderScheduler and to every notification channel already on a phone.
⚠️ Never leave an alarm.wav beside it: two files for one resource name is a
build error.

Committed on purpose. `res/raw/heartbeat.wav` was generated by a script that
was never committed, so that sound can't be regenerated or tweaked without
reverse-engineering it. Don't repeat that here.

Why a 30-second file: an Android notification sound plays *once*, it does not
loop. A 2-second beep is a notification; half a minute of beeping is what
actually wakes someone. Paired with `AudioAttributesUsage.alarm` (so it plays
on the alarm stream at alarm volume, not the muted notification stream) and
an ongoing full-screen-intent notification, that is as close to a real alarm
clock as the packages already in this project can get, with no new dependency
and no audio player.

Keep it in sync with ReminderScheduler._alarmSound ('alarm') and the
tools:keep entry in res/raw/keep.xml — a resource named only from Dart is
invisible to the release shrinker and gets stripped.
"""

import math
import os
import shutil
import struct
import subprocess
import tempfile
import wave

SAMPLE_RATE = 22050
DURATION_S = 30.0
AMPLITUDE = 0.55  # leaves headroom; the alarm stream is loud enough already

# One cycle: four short beeps, then a gap. The gap is what makes it read as
# an alarm rather than a fire panel — a continuous tone is easy to sleep
# through because it stops registering as new information.
BEEP_S = 0.10
GAP_S = 0.10
REST_S = 0.80
BEEPS_PER_CYCLE = 4

FUNDAMENTAL_HZ = 880.0
# A little third harmonic makes it piercing rather than flute-like. Any more
# and it turns to buzz.
HARMONIC_MIX = 0.22

# 5 ms of fade at each end of a beep. Without it every beep starts and ends
# on a discontinuity, which is an audible click on top of the tone.
EDGE_S = 0.005

OUT_PATH = os.path.join(
    "android", "app", "src", "main", "res", "raw", "alarm.ogg"
)

# Vorbis quality, 0 to 10. 4 is well past where a beep stops changing.
VORBIS_QUALITY = 4


def envelope(position_s: float, length_s: float) -> float:
    """Linear fade in/out so a beep can't click."""
    if position_s < EDGE_S:
        return position_s / EDGE_S
    remaining = length_s - position_s
    if remaining < EDGE_S:
        return max(0.0, remaining / EDGE_S)
    return 1.0


def build_cycle() -> list[float]:
    samples: list[float] = []
    for _ in range(BEEPS_PER_CYCLE):
        for i in range(int(BEEP_S * SAMPLE_RATE)):
            t = i / SAMPLE_RATE
            value = (
                math.sin(2 * math.pi * FUNDAMENTAL_HZ * t)
                + HARMONIC_MIX * math.sin(2 * math.pi * FUNDAMENTAL_HZ * 3 * t)
            ) / (1 + HARMONIC_MIX)
            samples.append(value * envelope(t, BEEP_S))
        samples.extend([0.0] * int(GAP_S * SAMPLE_RATE))
    samples.extend([0.0] * int(REST_S * SAMPLE_RATE))
    return samples


def main() -> None:
    cycle = build_cycle()
    total = int(DURATION_S * SAMPLE_RATE)
    frames = bytearray()
    for i in range(total):
        value = cycle[i % len(cycle)] * AMPLITUDE
        frames += struct.pack("<h", int(max(-1.0, min(1.0, value)) * 32767))

    if shutil.which("ffmpeg") is None:
        raise SystemExit("needs ffmpeg on the PATH to encode the Ogg Vorbis")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        raw = os.path.join(tmp, "alarm.wav")
        with wave.open(raw, "wb") as out:
            out.setnchannels(1)
            out.setsampwidth(2)
            out.setframerate(SAMPLE_RATE)
            out.writeframes(bytes(frames))
        subprocess.run(
            ["ffmpeg", "-y", "-loglevel", "error", "-i", raw,
             "-c:a", "libvorbis", "-q:a", str(VORBIS_QUALITY), OUT_PATH],
            check=True,
        )

    size = os.path.getsize(OUT_PATH)
    print(f"wrote {OUT_PATH} ({size / 1024:.0f} KB, {DURATION_S:.0f}s)")


if __name__ == "__main__":
    main()
