"""Generates android/app/src/main/res/raw/alarm.wav — the reminder alarm tone.

Run from the repo root:  python tools/generate_alarm_wav.py

Committed on purpose. `res/raw/heartbeat.wav` was generated by a script that
was never committed, so that sound can't be regenerated or tweaked without
reverse-engineering it. Don't repeat that here.

Why a 30-second file: an Android notification sound plays *once*, it does not
loop. A 2-second beep is a notification; half a minute of beeping is what
actually wakes someone. Paired with `AudioAttributesUsage.alarm` (so it plays
on the alarm stream at alarm volume, not the muted notification stream) and
an ongoing full-screen-intent notification, that is as close to a real alarm
clock as the packages already in this project can get, with no new dependency
and no audio player.

Keep it in sync with ReminderScheduler._alarmSound ('alarm') and the
tools:keep entry in res/raw/keep.xml — a resource named only from Dart is
invisible to the release shrinker and gets stripped.
"""

import math
import os
import struct
import wave

SAMPLE_RATE = 22050
DURATION_S = 30.0
AMPLITUDE = 0.55  # leaves headroom; the alarm stream is loud enough already

# One cycle: four short beeps, then a gap. The gap is what makes it read as
# an alarm rather than a fire panel — a continuous tone is easy to sleep
# through because it stops registering as new information.
BEEP_S = 0.10
GAP_S = 0.10
REST_S = 0.80
BEEPS_PER_CYCLE = 4

FUNDAMENTAL_HZ = 880.0
# A little third harmonic makes it piercing rather than flute-like. Any more
# and it turns to buzz.
HARMONIC_MIX = 0.22

# 5 ms of fade at each end of a beep. Without it every beep starts and ends
# on a discontinuity, which is an audible click on top of the tone.
EDGE_S = 0.005

OUT_PATH = os.path.join(
    "android", "app", "src", "main", "res", "raw", "alarm.wav"
)


def envelope(position_s: float, length_s: float) -> float:
    """Linear fade in/out so a beep can't click."""
    if position_s < EDGE_S:
        return position_s / EDGE_S
    remaining = length_s - position_s
    if remaining < EDGE_S:
        return max(0.0, remaining / EDGE_S)
    return 1.0


def build_cycle() -> list[float]:
    samples: list[float] = []
    for _ in range(BEEPS_PER_CYCLE):
        for i in range(int(BEEP_S * SAMPLE_RATE)):
            t = i / SAMPLE_RATE
            value = (
                math.sin(2 * math.pi * FUNDAMENTAL_HZ * t)
                + HARMONIC_MIX * math.sin(2 * math.pi * FUNDAMENTAL_HZ * 3 * t)
            ) / (1 + HARMONIC_MIX)
            samples.append(value * envelope(t, BEEP_S))
        samples.extend([0.0] * int(GAP_S * SAMPLE_RATE))
    samples.extend([0.0] * int(REST_S * SAMPLE_RATE))
    return samples


def main() -> None:
    cycle = build_cycle()
    total = int(DURATION_S * SAMPLE_RATE)
    frames = bytearray()
    for i in range(total):
        value = cycle[i % len(cycle)] * AMPLITUDE
        frames += struct.pack("<h", int(max(-1.0, min(1.0, value)) * 32767))

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with wave.open(OUT_PATH, "wb") as out:
        out.setnchannels(1)
        out.setsampwidth(2)
        out.setframerate(SAMPLE_RATE)
        out.writeframes(bytes(frames))

    print(f"wrote {OUT_PATH} ({len(frames) / 1024:.0f} KB, {DURATION_S:.0f}s)")


if __name__ == "__main__":
    main()
